# fly.toml app configuration file generated for strapi-demo-m on 2024-11-16T12:43:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strapi-demo-m'
primary_region = 'fra'

[env]
  TURBO_TELEMETRY_DISABLED = "1"

[build.args]
  APP="strapi-frontend"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
