# fly.toml app configuration file generated for strapi-test-faqsvw on 2024-11-15T07:52:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strapi-test-faqsvw'
primary_region = 'fra'

[env]
  HOST = "0.0.0.0"
  PORT = "3000"
  TURBO_TELEMETRY_DISABLED = "1"

[build.args]
  APP="strapi-backend"

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
