import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { fetchLayout } from "@/api/layout";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await fetchLayout();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          {(data.navigations as { Link: string; Title: string; id: string }[]).map(({ Link: navLink, Title, id }) => (
            <Link key={id} href={navLink}>{Title}</Link>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}